import type { Options } from "@wdio/types";

/**
 * WebDriverIO configuration for mset-ai-pipeline.
 *
 * To run the generated specs:
 *   1. Start Android emulator (Android Studio AVD or physical device)
 *   2. Start Appium server:  npx appium
 *   3. Install the APK on the emulator
 *   4. Run:  npx wdio run wdio.conf.ts
 *
 * Spec files are generated by the pipeline under:
 *   projects/<project-name>/output/specs/*.spec.ts
 */

export const config: Options.Testrunner = {

    // ── Runner ──────────────────────────────────────────────────────────────
    runner: "local",

    // ── Specs ───────────────────────────────────────────────────────────────
    // Points to all spec files generated by AutomationAgent across all projects
    specs: [
        "./projects/*/output/specs/**/*.spec.ts",
    ],
    exclude: [],

    // ── Capabilities (Android + Appium) ─────────────────────────────────────
    maxInstances: 1,
    capabilities: [{
        platformName: "Android",
        "appium:deviceName": "Android Emulator",
        "appium:platformVersion": "13.0",
        "appium:automationName": "UiAutomator2",
        "appium:app": "./apps/MyDemoApp.apk",
        "appium:appPackage": "com.saucelabs.mydemoapp.rn",
        "appium:appActivity": "com.saucelabs.mydemoapp.rn.MainActivity",
        "appium:noReset": false,
        "appium:autoGrantPermissions": true,
    }],

    // ── Appium / WebDriver ───────────────────────────────────────────────────
    port: 4723,
    services: [
        ["appium", {
            args: {
                address: "localhost",
                port: 4723,
                relaxedSecurity: true,
            },
            logPath: "./logs",
        }],
    ],

    // ── Framework ───────────────────────────────────────────────────────────
    framework: "mocha",
    mochaOpts: {
        ui: "bdd",
        timeout: 60000,
    },

    // ── Reporters ───────────────────────────────────────────────────────────
    reporters: [
        "spec",
        ["allure", {
            outputDir: "allure-results",
            disableWebdriverStepsReporting: true,
            disableWebdriverScreenshotsReporting: false,
        }],
    ],

    // ── TypeScript ───────────────────────────────────────────────────────────
    autoCompileOpts: {
        autoCompile: true,
        tsNodeOpts: {
            transpileOnly: true,
            project: "./tsconfig.json",
        },
    },

    // ── Timeouts ─────────────────────────────────────────────────────────────
    waitforTimeout: 10000,
    connectionRetryTimeout: 120000,
    connectionRetryCount: 3,

    // ── Hooks ─────────────────────────────────────────────────────────────────
    onPrepare() {
        console.log("mset-ai-pipeline — starting test run");
    },

    afterTest(test, _context, { error, passed }) {
        if (!passed) {
            console.log(`FAILED: ${test.fullName}`);
            if (error) console.log(error.message);
        }
    },

    onComplete(_exitCode, _config, _capabilities, results) {
        console.log(`Run complete. Passed: ${results.passed} | Failed: ${results.failed}`);
    },
};
